% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  english,
  ,man,floatsintext]{apa6}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={The truth revisited: Bayesian analysis of individual differences in the truth effect},
  pdflang={en-EN},
  pdfkeywords={Individual differences, qualitative differences, truth effect, hierarchical models, Bayesian model comparison},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
% Manuscript styling
\usepackage{upgreek}
\captionsetup{font=singlespacing,justification=justified}

% lle formatting
\usepackage{longtable}
\usepackage{lscape}
% \usepackage[counterclockwise]{rotating}   % Landscape page setup for large tables
\usepackage{multirow}		% Table styling
\usepackage{tabularx}		% Control Column width
\usepackage[flushleft]{threeparttable}	% Allows for three part tables with a specified notes section
\usepackage{threeparttablex}            % Lets threeparttable work with longtable

% Create new environments so endfloat can handle them
% \newenvironment{ltable}
%   {\begin{landscape}\begin{center}\begin{threeparttable}}
%   {\end{threeparttable}\end{center}\end{landscape}}
\newenvironment{lltable}{\begin{landscape}\begin{center}\begin{ThreePartTable}}{\end{ThreePartTable}\end{center}\end{landscape}}

% Enables adjusting longtable caption width to table width
% Solution found at http://golatex.de/longtable-mit-caption-so-breit-wie-die-tabelle-t15767.html
\makeatletter
\newcommand\LastLTentrywidth{1em}
\newlength\longtablewidth
\setlength{\longtablewidth}{1in}
\newcommand{\getlongtablewidth}{\begingroup \ifcsname LT@\roman{LT@tables}\endcsname \global\longtablewidth=0pt \renewcommand{\LT@entry}[2]{\global\advance\longtablewidth by ##2\relax\gdef\LastLTentrywidth{##2}}\@nameuse{LT@\roman{LT@tables}} \fi \endgroup}

% \setlength{\parindent}{0.5in}
% \setlength{\parskip}{0pt plus 0pt minus 0pt}

% \usepackage{etoolbox}
\makeatletter
\patchcmd{\HyOrg@maketitle}
  {\section{\normalfont\normalsize\abstractname}}
  {\section*{\normalfont\normalsize\abstractname}}
  {}{\typeout{Failed to patch abstract.}}
\makeatother
\shorttitle{Individual differences in the truth effect}
\author{Martin Schnuerch\textsuperscript{1}, Lena Nadarevic\textsuperscript{1}, \& Jeffrey N. Rouder\textsuperscript{2}}
\affiliation{
\vspace{0.5cm}
\textsuperscript{1} University of Mannheim\\\textsuperscript{2} University of California, Irvine}
\authornote{This research was supported by a grant from the Deutsche Forschungsgemeinschaft (DFG, GRK 2277) to the research training group Statistical Modeling in Psychology (SMiP).

Correspondence concerning this article should be addressed to Martin Schnuerch, B6, 30-32, 68159 Mannheim. E-mail: martin.schnuerch@psychologie.uni-mannheim.de}
\keywords{Individual differences, qualitative differences, truth effect, hierarchical models, Bayesian model comparison}
\usepackage{csquotes}
\usepackage{bm}
\usepackage{pcl}
\usepackage{amsmath}
\usepackage[utf8]{inputenc}
\usepackage{booktabs}
\usepackage{tabularx}
\usepackage{longtable,tabu}
\usepackage[font=footnotesize]{caption}
\ifxetex
  % Load polyglossia as late as possible: uses bidi with RTL langages (e.g. Hebrew, Arabic)
  \usepackage{polyglossia}
  \setmainlanguage[]{english}
\else
  \usepackage[shorthands=off,main=english]{babel}
\fi
\usepackage[style=apa,]{biblatex}
\addbibresource{bibliography.bib}
\addbibresource{lab.bib}

\title{The truth revisited: Bayesian analysis of individual differences in the truth effect}

\date{}

\abstract{
The repetition-induced truth effect refers to a phenomenon where people rate repeated statements as more likely true than novel statements. In this paper we document \emph{qualitative} individual differences in the effect. While the overwhelming majority of participants display the usual \emph{positive} truth effect, a minority are the opposite---they reliably discount the validity of repeated statements, what we refer to as \emph{negative} truth effect. We examine 8 truth-effect data sets where individual-level data are curated. These sets are composed of 1,105 individuals performing 38,904 judgments. Through Bayes factor model comparison, we show that reliable negative truth effects occur in 5 of the 8 data sets. The negative truth effect is informative because it seems unreasonable that the mechanisms mediating the positive truth effect are the same that lead to a discounting of repeated statements' validity. Moreover, the presence of qualitative differences motivates a different type of analysis of individual differences based on ordinal (i.e., Which sign does the effect have?) rather than metric measures. To our knowledge, this paper reports the first such reliable qualitative differences in a cognitive task.
}

\begin{document}
\maketitle

In the usual course of experimental psychology, we often understand phenomena by computing the mean effect. This mean effect may be used to compute effect sizes or statistical tests, and the resulting inferences are about the mean level in the population. In our view, this focus on the mean makes sense when all people experience a phenomenon in a qualitatively similar way. For example, suppose we ask people to identify a briefly-presented and subsequently masked letter. In this case, increasing the stimulus duration of the letter should affect every individual in the same direction, namely that longer durations correspond to better performance. It seems implausible in fact for any person's true performance to decreases with increasing stimulus duration. And it is in this sense, where we can be almost sure that a phenomenon affects people in a qualitatively similar manner, that recourse to the mean seems judicious.

What happens if a treatment affects different people differently? A good example might be the effect of aspirin. For most people, the drug aspirin safely relieves pain. Yet, a minority of the population are allergic to aspirin, and for these people, the allergic reaction may be serious. In this case, questions about the mean response seem unimportant. Instead, the important questions are what proportion of the population is allergic and what are the seperate mechanisms of pain relief and allergic reactions.

The question of whether the overall mean is useful hinges on whether an effect is qualitatively consistent across individuals. In the first example, it seems implausible that increasing the stimulus duration of a briefly flashed and subsequently masked object could decrease identification for anyone. For this example, the average performance gain as a function of stimulus duration seems a reasonable target for inquiry. For the aspirin example, however, average gain in pain relief seems far less helpful.

The key methodological question is how to tell if an effect is qualitatively consistent across a set of participants. Progress on this question has been made by Haaf and Rouder and colleagues \autocite{thiele2017,haaf2017,haaf2019}. We will review their approach subsequently, but for now, their research has yielded a startling finding. When it comes to performance tasks, it seems that people don't qualitatively differ. For example, nobody truly responds quicker to incongruent items in Stroop, Simon, or flanker tasks. Indeed, we are previously unaware of any case where substantial qualitative differences appear in a performance task. And this paper is the first we are aware of that shows such differences.

In this paper, we explore individual differences in a truth-judgment task. More precisely, the target of inquiry is a popular psychological effect, the repetition-based \emph{truth effect}. In a typical truth-effect task, participants rate how likely it is that a particular statement is true. The critical manipulation is repeating some statements, and these repeated statements are more likely rated as true than novel ones. The real world impact of the truth effect is obvious: If a lie is repeated, it is more likely to be believed.

The question we ask is whether all people are susceptible to what we call a \emph{positive} truth effect where repeated statements are judged as more valid than novel ones. The alternative is that some people have a true \emph{negative} truth effect where they tend to discount the validity of repeated statements. Here, we analyze data from eight previous experiments spanning 1,105 participants and 38,904 trials. We show to our surprise that in all the data sets where variation is detectable, there are some people who have a reliably negative truth effect. Most people show a positive truth effect, but a small minority truly discount the validity of repeated information.

\hypertarget{the-truth-effect}{%
\section{The Truth Effect}\label{the-truth-effect}}

Repeatedly encountering a piece of information is likely to increase the subjective belief in its validity. This phenomenon has been known -- and used -- for thousands of years. Around 150 BC, the Roman politician Cato reportedly concluded each of his speeches with the same sentence: ``Carthago delenda est'' (\textit{Carthage must be destroyed}). It seems that he succeeded in convincing the Roman Senate to approve of his proposition: In 146 BC, Carthage was destroyed. Cato's strategy might have resonated well with French military leader Napoleon Bonaparte, who conquered large parts of Europe in the early 19th century. According to Bonaparte, ``there is only one figure in rhetoric of serious importance, namely, repetition'' \autocite[p.~125]{lebon1895}. Roughly 100 years later, Nazi German Minister of Propaganda Joseph Goebbels made use of this rhetorical device; ``Repeat a lie often enough and it becomes the truth'', is typically attributed to Goebbels \autocite{stafford2016}.

The effect of repetition on the perception of a proposition's truth is a well-documented phenomenon in experimental psychology. In a seminal study, \textcite{hasher1977} asked participants to provide truth ratings for trivia statements in successive sessions. Critically, some of the statements were repeated across sessions while others were novel. The authors found validity ratings for repeated statements to increase, independent of the statements' actual validity, while ratings for novel statements did not change.

Over the past 40 years, the truth effect has been replicated numerous times \autocite{dechene2010,unkelbach2019}. It has been shown to be robust across different experimental designs, material, and instructions. Even explicit warnings about the effect do not eliminate it, but only reduce it \autocite{nadarevic2017}. The consequences of such a robust cognitive bias are evident: If used strategically, repeated dissemination increases belief even in false information \autocite{unkelbach2019,lazer2018,pennycook2018}.

Meta-analytic results indicate that the truth effect is stable across studies, and is medium in size \autocite[Cohen's \(d \approx 0.50\);][]{dechene2010}. Consequently, the truth effect has been well-established for the average of individuals. In contrast, we are aware of only a small number of published studies on individual differences \autocite{arkes1991,boehm1994,brashier2017,dekeersmaecker2020,newman2020,parks2006}. All of these studies assessed the covariation of individual truth effects and certain person-specific variables (e.g., age, need for cognition, and cognitive style). Yet, correlational analyses do not address the main question here, namely: Are individual differences only quantitative, or qualitative?

\textit{Quantitative} differences occur if all participants provide somewhat higher truth ratings for repeated than for novel statements. We might reasonably assume a common process underlying the effects in this case, and the mean might even be an adequate representation for understanding this process. The assumption is less reasonable, however, if differences are \emph{qualitative}, that is, if some participants were to depreciate the validity of repeated statements. Indeed, qualitative individual differences are precedented in the domain of truth judgments \autocite[i.e., belief polarization;][]{cook2016}. Is it still the same process that leads some people to increase their belief in repeated statements and others to decrease it? If qualitative differences can be shown, this has theoretical implications. A theory of the truth effect would have to account for both the increase and the decrease in beliefs due to repetition. Therefore, to gain constraint on theory, a fundamental question in the analysis of the repetition-based truth effect is what \textcite{haaf2017} coined the ``Does everybody?'' question: Does everybody show a positive truth effect?

This fundamental question comes with a methodological challenge: Even if we observe a negative truth effect for some individuals, this observation might reflect sampling noise rather than true qualitative differences. How do we assess whether people truly differ and, if so, whether these differences are qualitative? To answer these questions, we follow the strategy proposed by Haaf and Rouder \autocite*{haaf2017,haaf2019}. We develop a set of hierarchical Bayesian models that represent different structures of individual differences. By means of model comparison, we then directly assess the evidence from data about the nature of individual differences.

In the following, we provide a brief description of the eight data sets that we reanalyze in this study. We then develop the statistical models of individual-differences structures and outline the procedure to quantify evidence for these models. With model comparison, we find a surprising result: Across many of the data sets, there is a small proportion of individuals that show a negative truth effect.

\hypertarget{data-sets}{%
\section{Data Sets}\label{data-sets}}

We reanalyzed eight data sets from previous truth-effect experiments, all of which are publicly available from the Open Science Framework (OSF).\footnote{Set 1: \url{https://osf.io/6wv4z/}; Set 2: \url{https://osf.io/3uaj7/}; Sets 3 \& 4: \url{https://osf.io/5pfa2/}; Sets 5 \& 6: \url{https://osf.io/eut35/}; Set 7: \url{https://osf.io/b4szp/}; Set 8: \url{https://osf.io/txf46/}} Six of the sets have been published in peer-reviewed articles; two have been published only on OSF. Detailed information about the data and the experiments can be obtained from Appendix \ref{sec:data}.

All data sets are based on a common experimental design with three phases. Phase 1 is the \textit{exposure phase}: Participants see a number of trivia statements and, typically, assign each statement to a semantic domain (e.g., biology, geography, sports) or rate each for interest. Phase 2 is a retention interval, in wich participants may perform an unrelated task. This phase can range from a few minutes to several days. Phase 3 is the critical \textit{judgment phase} where participants rate the validity of statements. Ratings are typically given on a Likert scale, for example, from 1 (``definitely false'') to 6 (``definitely true''). Critically, half of the statements have been presented during the exposure phase and half are new. The truth effect is measured as the difference between mean truth ratings for repeated and for new statements, \(M_{rep} - M_{new}\).

For an overview of sample characteristics and results of the eight data sets, see Table \ref{tab:descriptives}. For the sake of comparison, we rescaled truth ratings to range from \(-1\) (``definitely false'') to \(1\) (``definitely true''). As a consequence, the truth effect can range from \(-2\) to \(2\). If all repeated statements received truth ratings of \(1\) while all new were rated as \(-1\), the resulting truth effect would be \(2\). An effect of \(-2\), in contrast, would indicate a perfect reversal of the truth effect. Zero represents the absence of any effect.

Figures \ref{fig:est1} and \ref{fig:est2} (left columns) show the individual truth effects in all eight data sets (black line). Individuals are sorted by the size of their effect, going from the most negative to the most positive. The red line indicates if the individual effect is below 0, that is, negative observed truth effects. The grey-shaded area surrounding the line denotes 95\% confidence intervals. The average effect across all people is given by the dashed horizontal line. In all data sets, we observe considerable differences between individual participants.

\begin{table}[tbp]

\begin{center}
\begin{threeparttable}

\captionsetup{font=normalsize,labelfont=normalsize}
\caption{\label{tab:descriptives}Summary of the Data Sets.}

\begin{tabular}{ccccccc}
\toprule
Set & Source & $N$ & $I$ & Mean Effect* & $t$ Test & Cohen's $d$\\
\midrule
1 & Nadarevic et al. (2012) & 267 & 20 & 0.20 (0.34) & $t$(266) = 9.47 & 0.58\\
2 & Nadarevic and Rinnewitz (2011) & 139 & 20 & 0.28 (0.36) & $t$(138) = 9.16 & 0.78\\
3 & Nadarevic and A{\ss}falg (2017), Exp. 1 & 33 & 88 & 0.11 (0.10) & $t$(32) = 6.54 & 1.14\\
4 & Nadarevic and A{\ss}falg (2017), Exp. 2 & 98 & 80 & 0.20 (0.23) & $t$(97) = 8.61 & 0.87\\
5 & Nadarevic and Erdfelder (2014), Exp. 1 & 85 & 88 & 0.05 (0.10) & $t$(84) = 5.09 & 0.55\\
6 & Nadarevic and Erdfelder (2014), Exp. 2 & 35 & 88 & 0.07 (0.17) & $t$(34) = 2.51 & 0.42\\
7 & Brashier et al. (2020), Exp. 1 & 52 & 120 & 0.09 (0.12) & $t$(51) = 5.52 & 0.77\\
8 & Pennycook et al. (2018), Exp. 1 & 396 & 20 & 0.14 (0.27) & $t$(395) = 10.08 & 0.51\\
\bottomrule
\addlinespace
\end{tabular}

\begin{tablenotes}[para]
\normalsize{\textit{Note.} $N$ = Number of participants; $I$ = Number of statements rated per participant; $t$ values and degrees of freedom are based on paired $t$ tests. *Standard deviation is given in parentheses.}
\end{tablenotes}

\end{threeparttable}
\end{center}

\end{table}

\begin{figure}
\includegraphics[width=1.5\textwidth]{p_files/figure-latex/est1-1} \caption{Observed (left column) and estimated (right column) individual truth effects for Data Sets 1--4, ordered by observed effect size. On the left side, the shaded area denotes individual 95\% confidence intervals. The dashed line represents average observed effects. On the right side, the shaded area denotes the 95\% credible interval. The grey line represents observed truth effects. Negative observed and estimated effects (i.e., higher truth ratings for novel than for repeated statements) are denoted by red color on both sides.}\label{fig:est1}
\end{figure}

\begin{figure}
\includegraphics[width=1.5\textwidth]{p_files/figure-latex/est2-1} \caption{Observed (left column) and estimated (right column) individual truth effects for Data Sets 5--8, ordered by observed effect size. On the left side, the shaded area denotes individual 95\% confidence intervals. The dashed line represents average observed effects. On the right side, the shaded area denotes the 95\% credible interval. The grey line represents observed truth effects. Negative observed and estimated effects (i.e., higher truth ratings for novel than for repeated statements) are denoted by red color on both sides.}\label{fig:est2}
\end{figure}

\hypertarget{statistical-models}{%
\section{Statistical Models}\label{statistical-models}}

The main substantive question is whether individual differences are quantitative or qualitative. Our strategy in answering this question is to implement each of these positions in statistical models, and then compare the models in light of data with Bayes factors. The specific models come from \textcite{haaf2017}, and, consequently, we provide only a brief overview here. Let \(Y_{ijk}\) denote the truth judgment of the \(i\)th person (\(i = 1, \ldots ,I\)) for the \(j\)th statemt (\(j = 1,\ldots, J\)) in condition \(k\) (\(k = 1,2\) for new versus repeated, respectively). Note that not every statement \(j\) is necessarily seen by each participant \(i\). Consequently, the data sets do not contain \(Y_{ijk}\) for every possible combination of \(i\), \(j\), and \(k\). This fact presents no problem in analysis.

We specify the following linear model on the dependent variable:
\begin{equation}
  Y_{ijk} \overset{\text{ind}}{\sim} \text{Normal} (\mu + \alpha_i + t_j \beta + x_k \theta_i,\ \sigma^2).
\end{equation}
In this model, \(\mu\) denotes the grand mean intercept and \(\alpha_i\) is a person-specific deviation from this grand mean. The term \(t_j\) codes the truth status of the \(j\)th statement, which can either be \(0\) if it is false, or \(1\) if it is true. Hence, \(\beta\) denotes the effect of a statement's factual truth on the judgment. The term \(x_k\) codes the repetition condition, which can either be \(0\) if the statement is new or \(1\) if it is repeated. Consequently, \(\theta_i\) denotes the \(i\)th individual's truth effect, and this parameter is the main target of inquiry. The last term, \(\sigma^2\), denotes the sampling variance of observed values. The main theoretical positions about individual differences motivate the following four models on \(\theta_i\):

\hypertarget{the-unconstrained-model}{%
\subsection{The Unconstrained Model}\label{the-unconstrained-model}}

The unconstrained model, \(\calM_u\), does not impose any constraints on the individual effects. It may be used to capture qualitative individual differences:
\begin{equation}
 \calM_u\text{: }\theta_i \overset{\text{iid}}{\sim} \text{Normal}(\nu,\ \delta^2).
\end{equation}
In this model, \(\nu\) and \(\delta^2\) denote the mean and variance of individual effects. These group-level parameters are estimated from the data.

\hypertarget{the-positive-effects-model}{%
\subsection{The Positive-Effects Model}\label{the-positive-effects-model}}

The positive-effects model, \(\calM_{+}\), is less flexible. It only allows for positive individual effects:
\begin{equation}
 \calM_{+}\text{: }\theta_i \overset{\text{iid}}{\sim} \text{Normal}_{+}(\nu,\ \delta^2).
\end{equation}
The distribution denoted by \(\text{Normal}_{+}\) is a truncated normal with a lower bound at zero. Thus, the model naturally incorporates the constraint that individuals may differ but they are all in the same predicted direction. Substantively, this model implies that differences are quantitative, but not qualitative.

\hypertarget{common-effect-model}{%
\subsection{Common-Effect Model}\label{common-effect-model}}

The critical specification in the common-effect model, \(\calM_1\), is that all individuals share one common effect:
\begin{equation}
 \calM_{1}\text{: }\theta_i = \nu.
\end{equation}
Accordingly, there are no true individual differences in the truth effect. Any observed variation would thus be due to sampling noise.

\hypertarget{null-model}{%
\subsection{Null Model}\label{null-model}}

The final model is a null model, \(\calM_0\), where there is no truth effect at all:
\begin{equation}
 \calM_{0}\text{: }\theta_i = 0.
\end{equation}
Accordingly, any observed effects of statement repetition are due to sampling noise.

Figure \ref{fig:modPred} (left column) illustrates the four models. On the x-axis, the true effect of a hypothetical participant is shown, \(\theta_1\). On the y-axis, the true effect of a second participant is shown, \(\theta_2\). The null model specifies that both effects are 0, thus, the model is represented by a point at the origin. The common-effect model does not restrict true effects to one value, but specifies that all individual effects are identical. This is represented by the diagonal line. No equality constraints are imposed in the positive-effects model, but all true individual effects are defined as larger than zero. Accordingly, \(\theta_1\) and \(\theta_2\) are free to vary in the upper-right quadrant. Finally, the unconstrained model puts no restrictions on individual effects; the model for the two hypothetical participants is represented by a bivariate normal centered at the origin.

\begin{figure}
\centering
\includegraphics{p_files/figure-latex/modPred-1.pdf}
\caption{\label{fig:modPred}Illustration of the four models (left column) on \(\theta_i\) and corresponding predictions (right column) for two hypothetical participants.}
\end{figure}

\hypertarget{prior-specification}{%
\subsection{Prior Specification}\label{prior-specification}}

We implement these models in the Bayesian framework, and, as such, priors are needed on parameters. For some parameters, those that are common in all four models, the priors may be set without undue influence on the posteriors or model comparison statistics. These specifications are provided in Appendix \ref{sec:priors}. For other parameters, however, those that vary across models (\(\theta\), \(\nu\), \(\delta^2\)), prior settings are important and are discussed here.

We follow the common \(g\)-prior specification approach \autocite{zellner1986}, which is based on placing priors on effect sizes. The setup is described in detail in \textcite{haaf2017} and \textcite{rouder2012}. Let \(g_\theta\) be a signal-to-noise ratio defined as \(g_\theta = \delta^2/\sigma^2\). This is an effect-size description of \(\theta\); it describes how much true variability there is across people relative to the variability in observations. With this parameter, we may write \(\theta_i \sim \mbox{Normal}(\nu,g_\theta\sigma^2)\). Priors are needed on \(\nu\) and \(g_\theta\). The prior on \(\nu\) is also scaled to the variability in observations: \(\nu \sim \mbox{Normal}(0,g_\nu\sigma^2)\), and there is a new parameter \(g_\nu\). Priors on these \(g\) parameters are Inverse-\(\chi^2\) distributions with one degree of freedom and a scale parameter \(r^2\):
\begin{equation}
\begin{split}
g_\nu & \sim \text{Inverse-}\chi^2(r_\nu^2),\\
g_\theta & \sim \text{Inverse-}\chi^2(r_\theta^2).
\end{split}
\end{equation}

Researchers need to set the scales of these priors before the analysis. We advocate that doing so should rely on substantive considerations rather than statistical arguments. Here is our line of thought: In our experience, on a standardized scale of \(-1\) to \(1\), truth judgments' trial-by-trial variability covers about a quarter of the scale, that is, \(\sigma = 0.50\). As a reference, on a scale from 1 to 6, this corresponds to a standard deviation of \(\sigma = 1.50\). When specifying \(r\), it is helpful to consider that it represents an expectation about the variability of the parameter relative to \(\sigma\). For example, a value of \(r_\theta = 1\) encodes the belief that the variability of person-specific truth effects (i.e., \(\delta\)) is comparable to the trial-by-trial variability. Likewise, \(r_\theta = 1/2\) or \(r_\theta = 2\) represent the expectation that \(\delta\) scales about half or about twice as large as \(\sigma\), respectively. Figure \ref{fig:priors} illustrates the effect of different choices of \(r_\theta\). It shows the resulting prior distributions on the variability of \(\theta_i\) conditional on a trial-by-trial variability of \(\sigma = 0.50\).

\begin{figure}
\centering
\includegraphics{p_files/figure-latex/priors-1.pdf}
\caption{\label{fig:priors}Prior distributions on \(\delta\), the variability of \(\theta_i\), for different scale settings. A trial-by-trial variation of \(\sigma = 0.50\) is assumed.}
\end{figure}

Based on this information, how do we choose the scale parameters? The average truth effect is of medium size, Cohen's \(d = 0.50\) \autocite{dechene2010}. Assuming \(\sigma = 0.50\), the expected observed effect on a rating scale of \(-1\) to \(1\) is thus \(0.25\). We find it reasonable to expect that the variability of this effect is of a comparable magnitude. Therefore, we define the scales of our \(g\) priors on \(\theta_i\) and \(\nu\) such that they place most weight on values around half the trial-by-trial variability, that is, \(r_\nu^2 = r_\theta^2 = (1/2)^2\).

\hypertarget{model-comparison}{%
\subsection{Model Comparison}\label{model-comparison}}

The models may be used to answer the main substantive question about qualitative individual differences. One approach is simply to estimate individual effects (\(\theta_i\)) in the full model. Yet, we think this approach is ultimately unhelpful. The problem is that whether there are qualitative differences between individuals is a global property rather than an individual one. One may know that someone must be negative without the ability to identify who. Consequently, individual estimates are not helpful in themselves. And population-level mean effects are not helpful either as they do not address the distinction between qualitative and quantitative individual differences. Hence, the key to assessment here may be made with model comparison and not with estimation.

A leading approach to model comparison in Bayesian analysis is the \textit{Bayes factor} \autocite{jeffreys1935,jeffreys1961}. Bayes factors measure the relativ strength of evidence for models by comparing how well these models predict the data \autocite{rouder2017,kass1995}. Figure \ref{fig:modPred} (right column) illustrates the predictions that the different models make for observed data of the two hypothetical participants. These predictions are noisy versions of the structure on true values. The more flexible a model is, that is, the fewer restrictions it imposes on the structure of individual differences, the more diffuse are its predictions. Hence, models are penalized for flexibility.

Analysis for the null model, the common-effect model, and the unconstrained model have been developed by \textcite{rouder2012}. Their approach is implemented in the \textit{BayesFactor} package \autocite{morey2015} in R \autocite{rcoreteam2019}, which allows for fast and accurate calculation of Bayes factors for three of the four models. This development, however, does not apply to the positive-effects model. Therefore, we calculated the Bayes factors between the positive-effects and the unconstrained model using the \textit{encompassing prior} method proposed by Klugkist and colleagues \autocite{klugkist2007,klugkist2005}. The combination of these two approaches is straightforward \parencite[e.g.,][]{haaf2017, haaf2019}.

\hypertarget{evidence-for-qualitative-differences}{%
\section{Evidence for Qualitative Differences}\label{evidence-for-qualitative-differences}}

\hypertarget{model-convergence}{%
\subsection{Model Convergence}\label{model-convergence}}

Posterior distributions for all parameters in the unconstrained model are obtained by Markov chain Monte Carlo (MCMC) sampling within the BayesFactor package. We checked model convergence by inspecting MCMC chains and computing autocorrelations for critical parameters (i.e., \(\nu\), \(\theta\), \(g_\nu\), and \(g_\theta\)). As in previous applications, the models converged fast and the chains mixed well. The autocorrelations for even the slowest converging parameters were inconsequential compared to the large number of posterior samples (10,000).

\hypertarget{estimation}{%
\subsection{Estimation}\label{estimation}}

Individual truth effect estimates from the unconstrained model for all eight data sets are shown in the right columns of Figures \ref{fig:est1} and \ref{fig:est2}. The black line denotes the posterior means of \(\theta_i\) for each participant. The grey band around this line is the 95\% credible interval, that is, an interval that contains 95\% of the posterior samples. The grey line represents observed individual truth effects and the ordering is obtained from these observed values (see left columns).

The first aspect to note is the effect of the hierarchical model specification on individual estimates. The effect is called shrinkage: Individual estimates inform each other and thus, outliers are pulled (\textit{shrunk}) toward the mean. This shrinkage is clearly visible in the estimates; there is less variability than in the observed effects. Note that the credible intervals are much smoother than the individual confidence intervals of observed effects (left column), reflecting regularization from the homogenous variance specification. The second aspect to note is that even with the shrunk estimates, considerable true individual differences remain. And the third aspect, perhaps the most consequential, is that some of these shrunk estimates are negative.

\hypertarget{model-comparison-1}{%
\subsection{Model Comparison}\label{model-comparison-1}}

Table \ref{tab:bfs} summarizes the results of the Bayes factor model comparison for the eight data sets. In each column, an asterisk marks the \emph{preferred} model, the one for which the data provided the most evidence. The other cells in each column show the Bayes factors between the remaining models and this preferred model. Because these remaining models are less preferred, the Bayes factors are always less than one, mostly by many orders of magnitude.

In five data sets, we find strong evidence for qualitative differences: In Sets 1, 2, 4, 6, and 8, the Bayes factors in favor of the unconstrained model \(\calM_u\) are at least 1000-to-1 over the next leading competitor. As \(\calM_u\) is the only model that allows for qualitative individual differences, the Bayes factors provide compelling evidence for them. In these data sets, there must be some individuals with a true negative truth effect.

In the remaining three data sets, in contrast, we do not find evidence for this negativity. Interestingly, the preferred model in Sets 3, 5, and 7 is not \(\calM_+\), which allows for quantitative individual differences. Instead, it is \(\calM_1\), which specifies a common effect without individual differences. In Sets 3 and 5, there is strong evidence for the common-effect model; the Bayes factors in favor of \(\calM_1\) are at least three orders of magnitude over the next competitor. In Set 7, in contrast, the evidence is fairly ambiguous, indicating that the data do not contain sufficient resolution to adjudicate among the different models. In summary, whenever we find individual differences, they are qualitative in nature rather than quantitative.

We find strong evidence for these differences in five data sets. In at least two, however, we find evidence against them. How do these two data sets, Sets 3 and 5, differ from the others? Looking for a psychological explanation, we note that in both sets the judgment phase was administered after a one-week retention interval, whereas it took place within one experimental session in all other sets. If this difference was systematic, the influence of retention-interval length could tell us something about the nature of individual differences. It is possible that differences in cognitive performance \autocite[e.g., source recollection;][]{begg1992} rather than personality underly qualitative differences in truth effects, and that these cognitive differences are affected for example by the length of the retention interval. Alternatively, however, there could be simple statistical reasons for this result: Data Set 3 is rather small, thus allowing for strong influence of shrinkage and making it difficult to evidence true individual differences should they exist. Therefore, we should be careful not to overinterpret the results. Any post-hoc explanation should be addressed and critically tested in future experiments.

\begin{table}
\captionsetup{font=normalsize,labelfont=normalsize}
\caption{\label{tab:bfs}Bayes Factor Model Comparison}
\centering
\resizebox{\linewidth}{!}{
\begin{threeparttable}
\begin{tabular}[t]{ccccccccc}
\toprule
\multicolumn{1}{c}{} & \multicolumn{8}{c}{Data Set} \\
\cmidrule(l{3pt}r{3pt}){2-9}
Model & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\\
\midrule
$\mathcal M_0$ & 3.2e-58 & 5.1e-57 & 4.1e-08 & 1.7e-124 & 8.9e-05 & 2.8e-07 & 3.8e-07 & 4.9e-41\\
$\mathcal M_1$ & 1.4e-20 & 8.8e-17 & * & 1.0e-49 & * & 5.9e-05 & * & 3.1e-09\\
$\mathcal M_+$ & 1.2e-03 & 1.1e-03 & 2.0e-03 & 1.1e-03 & 1.7e-07 & 8.7e-04 & 2.7e-01 & 1.2e-03\\
$\mathcal M_u$ & * & * & 1.9e-03 & * & 1.6e-04 & * & 2.0e-03 & *\\
\bottomrule
\end{tabular}
\begin{tablenotes}[para]
\item \textit{Note.} 
\item The preferred model for each data set is indicated by an asterisk. Remaining cells contain Bayes factors for each model against the preferred model. $\mathcal M_0$ = null model; $\mathcal M_1$ = common-effect model; $\mathcal M_+$ = positive-effects model; $\mathcal M_u$ = unconstrained model.
\end{tablenotes}
\end{threeparttable}}
\end{table}

\hypertarget{classifying-individuals}{%
\section{Classifying Individuals}\label{classifying-individuals}}

Who are these individuals that depreciate the validity of repeated statements? Posterior means, such as those in Figures \ref{fig:est1} and \ref{fig:est2}, do not provide enough information for classification because classification should depend on the underlying variability. A better approach to classifying individuals with truly negative truth effects is to assess the posterior probability that an individual's estimate is less than 0.

Figure \ref{fig:probs} shows the posterior probability of a \emph{positive} truth effect for each individual, that is, \(P(\theta_i > 0|\text{Data})\). The red color denotes individuals with negative posterior means. As a means to classify people for the purposes of this article, we assign individuals with a probability of at least 3-to-1 to one of two groups: We define individuals with \(P(\theta_i > 0|\text{Data}) \geq .75\) as \emph{positive truthers}. In contrast, individuals with \(P(\theta_i > 0|\text{Data}) \leq .25\) are \emph{negative truthers}. We classify participants with \(.25 \leq P(\theta_i > 0|\text{Data}) \leq .75\) as undecided. We acknowledge that this way to classify people is somewhat arbitrary. That notwithstanding, across all data sets, 70.05\% of all participants are classified as positive truthers; only 1.09\% are classified as negative truthers and 28.87\% are classified as undecided.

In Sets 3 and 5, we found strong evidence for the absence of individual differences. Yet, while no individuals classify as negative truthers in these data sets, we still find 22.03\% to be undecided. This result shows that classification may find differences even when a more global approach---model comparison---indicates that these differences are unwarranted. A somewhat complimentary state-of-affairs occurs for Data Set 6. Here, model comparison showed strong evidence for qualitative individual differences. Yet, we cannot classify anyone with certainty as a negative truther.

These discrepencies illustrate the difficulty with classification: When we apply a classification approach, we may classify individuals as different even when there are no true individual differences. This state occurs because classification is local to the individual, and as such, it is more susceptible to noise than Bayes factor assessment of global patterns. Conversely, we may know from the Bayes factor global assessment that a set may have at least one individual with a true negative effect. Yet, based on individual posterior probabilities, it may be difficult to know which one that is.

The aim of this paper is the global assessment of individual difference patterns in truth-effect experiments. If our overriding goal was to classify people, we could construct a latent-class classification model. In such a model, the normal in the unconstrained model could be replaced with a mixture of two states. One state would cover the positive truthers; and the distribution would be limited to positive true values. The other would cover the negative truthers, and the distribution would be limited to negative true values. If there is little mass toward zero, the model would have the effect of cleaving people clearly into two groups. A good example here is \textcite{houpt2017}, who used this latent-class approach to classify people as using either serial or parallel processing in a systems factorial setting. The development of such a model is beyond the scope of this paper, but may prove useful in understanding the relationship between individual differences in the truth effect and other variables.

\begin{figure}
\includegraphics[width=1.5\textwidth]{p_files/figure-latex/probs-1} \caption{Individual posterior probabilities of a positive truth effect. Participants are ordered by observed effect size. The red line denotes individuals with negative posterior means (see Figures \ref{fig:est1} and \ref{fig:est2}).}\label{fig:probs}
\end{figure}

\hypertarget{sensitivity-to-prior-settings}{%
\section{Sensitivity to Prior Settings}\label{sensitivity-to-prior-settings}}

\begin{figure}
\centering
\includegraphics{p_files/figure-latex/sensitivity-1.pdf}
\caption{\label{fig:sensitivity}Sensitivity of Bayes factor model comparison to different prior settings. Shown are Bayes factors for each model against the preferred model. The asterisk denotes the prior setting used in the previous analysis. Details for each prior setting are shown in Table \ref{tab:priorsettings}.}
\end{figure}

The Bayesian analysis presented herein requires the analyst to set a prior scale, denoted \(r^2\), on the signal-to-noise ratio \(g\). The dependence of Bayesian analysis on prior settings is frequently criticized as posing a threat as it provides for uncounted researcher degrees of freedom \autocite{Simmons:etal:2011}. Indeed, it seems reasonable to require that for the same data set, different researchers should reach the same conclusions. Yet, almost all Bayesians note that priors have effects on inference. To align Bayesian inference with the above desideratum, many Bayesian analysts actively seek to minimize the effects of prior settings \autocites[e.g.,][]{aitkin1991}{Gelman:etal:2004}{kruschke2013}{spiegelhalter2002}.

We do not subscribe to the view that minimization of prior effects is necessary or even laudable. In fact, all reasonable statistical procedures that we are aware of require the researcher to make decisions that will affect the inference (e.g., choosing the sample size). The choice of prior settings is important because it affects the predictions that models make about data. Therefore, these settings that affect the predictive accuracy of a model \emph{should} affect our opinions about it in light of data.

Thus, when different researchers use different priors, they may reach different opinions about the data. \textcite{rouder2016a} argue that so long as various prior settings are \emph{justifiable,} the variation in results should be embraced as the legitimate diversity of opinion. When reasonable prior settings result in conflicting conclusions, we may infer that the data do not afford the precision to adjudicate among competing positions.

With this argument in mind, we may assess whether reasonable variation in prior settings affects Bayes factor conclusions about the nature of individual differences in the truth effect for the current data. To that end, we repeated the above analysis with a number of different prior settings. The critical settings are \(r_\nu\) and \(r_\theta\), which code the scale of effects. We set \(r_\nu\) and \(r_\theta\) to \(0.50\) in value, meaning that we expect the variation in \(\nu\) and \(\theta\) to be about half the variation in repeated observations. Here, we allow each of these settings to be this value, half this value, and twice this value; and the factoral combination yields nine possible settings. We computed the Bayes factors for all models for all nine settings for all data sets to understand how reasonable variation in prior settings affects inference.

For seven of eight data sets, model comparison was unaffected by reasonable variation in prior settings. As an illustration, the results for two data sets are depicted in Figure \ref{fig:sensitivity}. The figure shows the Bayes factors for all models relative to the preferred one in the previous analysis. On the right is Data Set 7, the most concerning. Here, the common-effect model is preferred only by a negligible amount depending on the prior setting, indicating a lack of a clear verdict between the models. This lack of resolution holds only for this data set. The left panel shows the case for Data Set 6, and we chose this set because, outside of Data Set 7, Bayes factors were most dependent on prior settings. Even so, the unconstrained model is preferred over all other models by at least a factor of 100 across the range of reasonable prior settings. In the remaining data sets (not shown), there is even more stability of Bayes factors across the ranges. Hence, across reasonable variation in prior settings, Data Sets 1, 2, 4, 6, and 8 show strong evidence for qualitative individual differences. In a similar fashion, the common-effect model is clearly preferred for all prior settings in Data Sets 3 and 5. Overall, the results presented here are robust to a wide range of reasonable prior opinion.

\begin{table}

\captionsetup{font=normalsize,labelfont=normalsize}
\caption{\label{tab:priorsettings}Prior Settings for Sensitivity Analysis}
\centering
\begin{threeparttable}
\begin{tabular}[t]{cccccccccc}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{9}{c}{Prior Setting} \\
\cmidrule(l{3pt}r{3pt}){2-10}
Parameter & A & B & C & D & E & F & G & H & *\\
\midrule
$r_\nu$ & 1/4 & 1/4 & 1/4 & 1/2 & 1/2 & 1 & 1 & 1 & 1/2\\
$r_\theta$ & 1/4 & 1/2 & 1 & 1/4 & 1 & 1/4 & 1/2 & 1 & 1/2\\
\bottomrule
\end{tabular}
\begin{tablenotes}[para]
\item \textit{Note.} 
\item The asterisk codes the prior setting used in the previous analysis.
\end{tablenotes}
\end{threeparttable}
\end{table}

\hypertarget{general-discussion}{%
\section{General Discussion}\label{general-discussion}}

In this paper, we show a surprising finding. Although the truth effect is reliably obtained across many data sets, the effect itself is inconsistent across people. We are confident that in most experiments some people truly judge repeated statements as more valid than novel ones, while others truly judge them as less so. This effect is not just noise---the models indicate that this inconsistency occurs above and beyond trial-by-trial variation. What makes the finding surprising to us is that the result is in contrast to previous work with these individual-difference models. The modal result is that ``everybody does'', that is, there are no qualitative individual differences in common cognitive effects such as Stroop and Flanker effects \autocite{haaf2017,haaf2019}. In the repetition-based truth effect, these differences exist, and they occur consistently across several data sets.

Does the presence of qualitative individual differences inform current cognitive theories of the truth effect? We think it should. A number of theoretical explanations have been proposed for the repetition-based truth effect, for example, the recognition account \autocite{bacon1979}, the source-dissociation hypothesis \autocite{arkes1991}, the familiarity account \autocite{begg1992}, processing fluency \autocite{reber1999}, or the referential theory \autocite{unkelbach2017}. These accounts assume different underlying cognitive mechanisms, yet, they all make the same core prediction: repetition increases perceived validity. \textcite{unkelbach2019} summarize thusly: ``No matter which mental processes may underly the repetition-induced truth effect, on a functional level, repetition increases subjective truth'' (p.~5). We argue, based on our analysis, that this statement is too general. In fact, we show what \textcite{davis-stober2019} call the \emph{paradox of converging evidence}: Across data sets, we find converging evidence that the statement holds on the mean level---yet, at the same time, we accumulate strong evidence that it doesn't hold for everybody. Consequently, our results present converging evidence against theoretical positions that do not account for negative truthers.

\section{Open Practices Statement}

All data used in this study are publicly available from their original OSF repositories (links have been provided in the text). The reanalysis was not preregistered. This paper is written in RMarkdown which includes all code for analyses and figures. The RMarkdown and all supporting files are curated at \url{https://github.com/PerceptionAndCognitionLab/hc-truth/tree/public}.

\printbibliography

\clearpage
\makeatletter
\efloat@restorefloats
\makeatother


\begin{appendix}
\hypertarget{description-of-data-sets}{%
\section{Description of Data Sets}\label{description-of-data-sets}}

\label{sec:data}

\hypertarget{set-1}{%
\subsection{Set 1}\label{set-1}}

Set 1 contains data from an unpublished study by
\textcite{nadarevic2012} on the association of personality traits and
the truth effect. In this web-based study, participants were presented
with 20 trivia statements, half of which were true and half were false.
Participants were informed that statements could be either true or
false, and asked to assign each to one of five knowledge categories. In
a subsequent phase, participants completed a number of personality
questionnaires. Finally, participants were again presented with 20
trivia statements and asked to provide a truth rating on a scale from 1
to 5 for each statement. Ten of these statements had been presented in
Phase 1, the other ten statements were new.

In total, 267 participants completed the study. Mean truth ratings for
repeated statements were higher than for new statements,
\(M_\text{rep} - M_\text{new} =\) 0.20 (\(SD\) = 0.34). A two-sided
\(t\) test for paired samples revealed a significant truth effect,
\(t(266) = 9.47\), \(p < .001\), Cohen's \(d = 0.58\).

\hypertarget{set-2}{%
\subsection{Set 2}\label{set-2}}

Data Set 2 is from \textcite{nadarevic2011}. In the exposure phase,
participants were asked to assign 20 unknown trivia statements to one of
five knowledge categories. After completing a personality questionnaire
in the retention phase, participants were asked to provide truth ratings
for 20 statements on a scale from 1 to 5. Ten of these statements were
repeated from the exposure phase, the others were new. As an
experimental manipulation, one group of participants was instructed to
respond intuitively, while the other was asked to think carefully about
each truth judgment. This manipulation did not have any systematic
effect on truth judgments, however. Therefore, we did not include the
factor condition in the analysis. The total sample comprised 139
participants. On average, truth jdugments for repeated statements were
higher than for new statements, \(M_\text{rep} - M_\text{new} =\) 0.28
(\(SD\) = 0.36). This difference is statistically significant,
\(t(138) = 9.16\), \(p < .001\), Cohen's \(d = 0.78\).

\hypertarget{set-3}{%
\subsection{Set 3}\label{set-3}}

Data Set 3 is based on Experiment 1 in \textcite{nadarevic2017} who
investigated the influence of warnings on the truth effect. For the
analysis, we only included data from the control group, which received
standard instructions and no warnings. The sample comprises 33 students
who participated in the lab-based study. In Phase 1, participants
assigned 98 statements (including ten buffer statements) to knowledge
categories. After a one-week retention interval, they returned to the
lab and provided truth statements on a scale from 1 to 6 for 44
statements from Phase 1 and 44 new statements. Truth statements for
repeated items were significantly higher than for new statements,
\(M_\text{rep} - M_\text{new} =\) 0.11 (\(SD\) = 0.10),
\(t(32) = 6.54\), \(p < .001\), Cohen's \(d = 1.14\).

\hypertarget{set-4}{%
\subsection{Set 4}\label{set-4}}

For Set 4, we used data from Nadarevic and A\ss falg's
\autocite*{nadarevic2017} Experiment 2. It was identical to the first
experiment with the exception that the exposure phase was directly
followed by the judgment phase and participants rated 80 statements,
half of which were repeated. As in the previous data set, we only
included the control condition in the analysis. The set contains 98
participants. On the mean level, there is a significant truth effect:
\(M_\text{rep} - M_\text{new} =\) 0.20 (\(SD\) = 0.23),
\(t(97) = 8.61\), \(p < .001\), Cohen's \(d = 0.87\).

\hypertarget{set-5}{%
\subsection{Set 5}\label{set-5}}

Data Set 5 is based on Experiment 1 reported in
\textcite{nadarevic2014}. The authors investigated the influence of
Phase-1 task and retention interval between exposure and judgment phase
on the truth effect. Unlike in the previous experiments, participants
were asked to rate the statements' validity already in Phase 1. In two
subsequent truth-judgment phases, participants rated the statements
again: One was administered after ten minutes (Phase 2), another one
after one week (Phase 3). Half of the statements from Phase 1 were
repeated in Phase 2, the other half was repeated in Phase 3. Truth
judgments in Phase 1 and a retention interval of several days is a
commonly used setting in truth-effect experiments
\autocite[e.g.,][]{hasher1977}. In contrast, rating the statements'
truth in Phase 1 and again after a short retention interval does not
lead to a truth effect. Therefore, we only included truth judgments from
Phase 3 in the analysis. The sample comprised 85 participants and 88
truth judgments on a scale from 1 to 6 per participant. Analysis of mean
truth ratings for repeated and new statements revealed a significant
truth effect: \(M_\text{rep} - M_\text{new} =\) 0.05 (\(SD\) = 0.10),
\(t(84) = 5.09\), \(p < .001\), Cohen's \(d = 0.55\).

\hypertarget{set-6}{%
\subsection{Set 6}\label{set-6}}

Set 6 contains data from Experiment 2 in \textcite{nadarevic2014}.
Participants were assigned to one of two experimental conditions. In one
condition, as in Experiment 1, participants rated the truth of each
statement in Phase 1. In the other condition, participants assigned the
statements to knowledge categories. After a ten minute retention
interval, participants in both groups provided truth statements for 88
statements, half of which were repeated from Phase 1. We only included
data from the category-rating condition in the analysis. The sample
comprised 35 participants. Average truth ratings for repeated statements
were significantly higher than for new statements,
\(M_\text{rep} - M_\text{new} =\) 0.07 (\(SD\) = 0.17),
\(t(34) = 2.50\), \(p = .017\), Cohen's \(d = 0.42\).

\hypertarget{set-7}{%
\subsection{Set 7}\label{set-7}}

Data Set 7 is based on Experiment 1 reported in \textcite{brashier2020}.
Similar to Nadarevic and Erdfelder's \autocite*{nadarevic2014}
Experiment 2, participants initially rated 60 statements either for
truthfulness or for interest on a scale from 1 to 6. In the judgment
phase, they provided truth ratings for these statements and 60
additional statements. We included the data from the interest-rating
condition in the analysis. The data set contains 52 participants. The
average difference in truth ratings was
\(M_\text{rep} - M_\text{new} =\) 0.09 (\(SD\) = 0.12), revealing a
significant truth effect: \(t(51) = 5.52\), \(p < .001\), Cohen's
\(d = 0.77\).

\hypertarget{set-8}{%
\subsection{Set 8}\label{set-8}}

For the last data set, we included data from Experiment 1 reported in
\textcite{pennycook2018}. Participants rated the interestingness of 14
trivia statements in the first phase. After a short retention interval,
participants rated the same statements and 14 additional statements in
terms of truthfulness on a scale from 1 to 6. Eight of these 28
statements were likely to be known by all participants, the other 20
statements were largely unknown. In the reanalysis, we included truth
ratings for the 20 unknown statements. We excluded 13 participants due
to missings that occurred during the judgment phase. The final data set
comprises 396 participants. On average, truth judgments for repeated
statements were higher than for new statements,
\(M_\text{rep} - M_\text{new} =\) 0.14 (\(SD\) = 0.27), revealing a
significant truth effect: \(t(395) = 10.08\), \(p < .001\), Cohen's
\(d = 0.51\).
\end{appendix}

\clearpage
\makeatletter
\efloat@restorefloats
\makeatother


\begin{appendix}
\hypertarget{prior-specifications}{%
\section{Prior Specifications}\label{prior-specifications}}

\label{sec:priors}

The parameters \(\alpha_i\), \(\beta\), \(\mu\), and \(\sigma^2\) are
common to all models. We place a noninformative and scale-invariant
prior called \textit{Jeffreys prior} \autocite{jeffreys1961} on the
non-effect parameters \(\mu\) and \(\sigma^2\): \begin{equation}
\pi(\mu,\ \sigma^2) \propto \dfrac{1}{\sigma^2}.
\end{equation}

Priors on the remaining parameters are defined as functions of
\(\sigma^2\), the variance of the observed variable. We specify the
following prior for person-specific intercepts \begin{equation}
\begin{split}
\label{eq:prior_alpha}
\alpha_i &\overset{\text{iid}}{\sim} \text{Normal}(0,\ g_\alpha \sigma^2),\\
g_\alpha &\sim \text{Inverse-}\chi^2(r_\alpha^2).
\end{split}
\end{equation}

We expected the variability in people's individual baselines to be about
twice as large as the inter-trial variability. Therefore, we set
\(r_\alpha^2 = 2^2\). Note that the inverse-\(\chi^2\) distribution has
fat tails and, given sufficient data, will be overruled by the data if
the observed variability differs strongly from what we expected.

We apply a similar reasoning to the effect of factual truth, \(\beta\).
We define \begin{equation}
\begin{split}
\beta &\sim \text{Normal}(0,\ g_\beta \sigma^2),\\
g_\beta &\sim \text{Inverse-}\chi^2(r_\beta^2),
\end{split}
\end{equation} and set \(r_\beta^2 = 2^2\). Sensitivity analyses
revealed that results did not differ meaningfully for any choice of
\(r_\alpha^2,\ r_\beta^2 \in [0.25, 16]\).
\end{appendix}

\end{document}
